[tool.poetry]
name = "stonkgame"
version = "0.1.0"
description = ""
authors = ["Appleplectic <llmar1000000@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pynput = "^1.7.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
